### ISSUE TITLE
Generate RouteNames

### ISSUE THREAD

**Issue by HannesVDB** [icapps/flutter-icapps-generator#18]
When generating a new screen. A `routeName` is created in the `Widget`
Since I'd like to group all the different `routeName`s in one class I've created a singleton
```
class RouteNames {
  RouteNames._();
  static const homeScreen = 'home';
  static const debugScreen = 'debug';
  static const splashScreen = 'splash';
}
``` 

Therefore I'd like to see if it's possible to update the generator so that instead of the static string we could use the `RouteNames` and generate the static const when creating a new screen?

**Comment by vanlooverenkoen** [comment]
Fixed
